# Hand-coded ecological traits for Baltic Sea / Kattegat species
# salinity_min/max in PSU; depth_zone: supralittoral/littoral/infralittoral/circalittoral/profundal
# functional_group: emergent_macrophyte/submerged_macrophyte/floating_macrophyte/macroalga/
#   filter_feeder/deposit_feeder/predator/suspension_feeder/epibenthic
# substrate: rock/sand/mud/soft/plant/mixed/pelagic
# sal_midpoint: midpoint of tolerance range (used for numeric metrics)

TIER1_TRAITS = {
    # ── FRESHWATER / OLIGOHALINE MACROPHYTES ──────────────────────────────────
    "Potamogeton obtusifolius":   {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Potamogeton natans":         {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "floating_macrophyte",   "substrate": "soft"},
    "Potamogeton perfoliatus":    {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Potamogeton gramineus":      {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Potamogeton berchtoldii":    {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Potamogeton friesii":        {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Potamogeton pusillus":       {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Potamogeton crispus":        {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Potamogeton praelongus":     {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Schoenoplectus lacustris":   {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Schoenoplectus tabernaemontani": {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 5, "depth_zone": "littoral",    "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Typha angustifolia":         {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Typha latifolia":            {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Caltha palustris":           {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Nymphaea alba":              {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "floating_macrophyte",   "substrate": "soft"},
    "Nuphar lutea":               {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "floating_macrophyte",   "substrate": "soft"},
    "Equisetum fluviatile":       {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Sagittaria sagittifolia":    {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Sagittaria natans":          {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Sparganium emersum":         {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Elodea canadensis":          {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Elodea nuttallii":           {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Myriophyllum verticillatum": {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Myriophyllum alterniflorum": {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Myriophyllum spicatum":      {"salinity_min": 0, "salinity_max": 10, "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Myriophyllum sibiricum":     {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Ceratophyllum demersum":     {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Utricularia vulgaris":       {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Najas marina":               {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Stuckenia pectinata":        {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 5,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Stuckenia vaginata":         {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Nitellopsis obtusa":         {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Callitriche hermaphroditica":{"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Callitriche palustris":      {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Ranunculus aquatilis":       {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Ranunculus reptans":         {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Ranunculus peltatus peltatus":{"salinity_min": 0,"salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Eleocharis palustris":       {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Eleocharis acicularis":      {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Eleocharis mamillata":       {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Eleocharis uniglumis":       {"salinity_min": 0, "salinity_max": 10, "sal_midpoint": 3,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Eleocharis parvula":         {"salinity_min": 0, "salinity_max": 10, "sal_midpoint": 3,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Elatine hydropiper":         {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Limosella aquatica":         {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Subularia aquatica":         {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "sand"},
    "Alisma wahlenbergii":        {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Butomus umbellatus":         {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Cicuta virosa":              {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Crassula aquatica":          {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Persicaria foliosa":         {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Hippuris vulgaris":          {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 2,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Hippuris tetraphylla":       {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 2,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Phragmites australis":       {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 3,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Bolboschoenus maritimus":    {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 5,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Lemna minor":                {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "littoral",       "functional_group": "floating_macrophyte",   "substrate": "pelagic"},
    "Lemna trisulca":             {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "floating_macrophyte",   "substrate": "pelagic"},
    "Juncus gerardii":            {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "supralittoral",  "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    "Triglochin maritima":        {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "supralittoral",  "functional_group": "emergent_macrophyte",   "substrate": "soft"},
    # ── CHAROPHYTES ────────────────────────────────────────────────────────────
    "Chara aspera":               {"salinity_min": 0, "salinity_max": 10, "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Chara tomentosa":            {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 2,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Chara connivens":            {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 2,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Chara baltica":              {"salinity_min": 0, "salinity_max": 12, "sal_midpoint": 4,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Chara canescens":            {"salinity_min": 2, "salinity_max": 15, "sal_midpoint": 6,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Chara horrida":              {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Chara braunii":              {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Chara virgata":              {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Nitella flexilis":           {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Nitella wahlbergiana":       {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    # ── FRESHWATER ALGAE / BRYOPHYTES ──────────────────────────────────────────
    "Aegagropila linnaei":        {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "soft"},
    "Fontinalis antipyretica":    {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Fontinalis dalecarlica":     {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Fontinalis hypnoides":       {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Fissidens fontanus":         {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Batrachospermum":            {"salinity_min": 0, "salinity_max": 2,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Ulothrix zonata":            {"salinity_min": 0, "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "littoral",       "functional_group": "macroalga",             "substrate": "rock"},
    "Zygnema":                    {"salinity_min": 0, "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "soft"},
    "Monostroma balticum":        {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Vaucheria":                  {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 5,  "depth_zone": "littoral",       "functional_group": "macroalga",             "substrate": "soft"},
    # ── BRACKISH / TRANSITIONAL SEAGRASSES ─────────────────────────────────────
    "Zannichellia palustris":     {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 5,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Zannichellia major":         {"salinity_min": 0, "salinity_max": 10, "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Ruppia maritima":            {"salinity_min": 2, "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Ruppia cirrhosa":            {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "soft"},
    "Zostera marina":             {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte",  "substrate": "sand"},
    # ── BRACKISH MACROALGAE ─────────────────────────────────────────────────────
    "Fucus vesiculosus radicans": {"salinity_min": 3, "salinity_max": 15, "sal_midpoint": 7,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Chorda filum":               {"salinity_min": 3, "salinity_max": 25, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "sand"},
    "Ceramium tenuicorne":        {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Ectocarpus Pylaiella":       {"salinity_min": 2, "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Furcellaria lumbricalis":    {"salinity_min": 3, "salinity_max": 25, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Coccotylus Phyllophora":     {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Elachista fucicola":         {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Stictyosiphon tortilis":     {"salinity_min": 3, "salinity_max": 15, "sal_midpoint": 7,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Dictyosiphon foeniculaceus": {"salinity_min": 3, "salinity_max": 15, "sal_midpoint": 7,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Eudesme virescens":          {"salinity_min": 3, "salinity_max": 18, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Vertebrata fucoides":        {"salinity_min": 3, "salinity_max": 18, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Gaillona rosea":             {"salinity_min": 3, "salinity_max": 15, "sal_midpoint": 7,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Cladophora rupestris":       {"salinity_min": 3, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Rhizoclonium riparium":      {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 5,  "depth_zone": "littoral",       "functional_group": "macroalga",             "substrate": "soft"},
    "Chaetomorpha linum":         {"salinity_min": 2, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "soft"},
    "Ulva prolifera":             {"salinity_min": 2, "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Leathesia marina":           {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Urospora penicilliformis":   {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "littoral",       "functional_group": "macroalga",             "substrate": "rock"},
    "Battersia arctica":          {"salinity_min": 3, "salinity_max": 18, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Rhodochorton purpureum":     {"salinity_min": 3, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Cladophora sericea":         {"salinity_min": 3, "salinity_max": 25, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Ceramium virgatum":          {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Dumontia contorta":          {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Scytosiphon lomentaria":     {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "littoral",       "functional_group": "macroalga",             "substrate": "rock"},
    "Mesogloia vermiculata":      {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Polysiphonia elongata":      {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Polysiphonia stricta":       {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Ahnfeltia plicata":          {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Rhodomela confervoides":     {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Chordaria flagelliformis":   {"salinity_min": 2, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Dictyosiphon chordaria":     {"salinity_min": 2, "salinity_max": 15, "sal_midpoint": 6,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Spongonema tomentosum":      {"salinity_min": 5, "salinity_max": 20, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Halosiphon tomentosus":      {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Spongomorpha aeruginosa":    {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Spermatochnus paradoxus":    {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    # ── BRACKISH INVERTEBRATES ──────────────────────────────────────────────────
    "Mytilus":                    {"salinity_min": 3, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Amphibalanus improvisus":    {"salinity_min": 3, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Mya arenaria":               {"salinity_min": 3, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Cerastoderma glaucum":       {"salinity_min": 2, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Cerastoderma edule":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Hediste diversicolor":       {"salinity_min": 0, "salinity_max": 35, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Pygospio elegans":           {"salinity_min": 2, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Limecola balthica":          {"salinity_min": 2, "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Marenzelleria":              {"salinity_min": 2, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Corophium volutator":        {"salinity_min": 2, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Corophium multisetosum":     {"salinity_min": 2, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Gammarus salinus":           {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Gammarus oceanicus":         {"salinity_min": 3, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "rock"},
    "Gammarus zaddachi":          {"salinity_min": 0, "salinity_max": 15, "sal_midpoint": 5,  "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Gammarus tigrinus":          {"salinity_min": 0, "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Neomysis integer":           {"salinity_min": 0, "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "pelagic"},
    "Bathyporeia pilosa":         {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Jaera albifrons":            {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "littoral",       "functional_group": "predator",              "substrate": "rock"},
    "Peringia ulvae":             {"salinity_min": 3, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "littoral",       "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Ecrobia ventrosa":           {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Theodoxus fluviatilis":      {"salinity_min": 0, "salinity_max": 10, "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "rock"},
    "Cyanophthalma obscura":      {"salinity_min": 3, "salinity_max": 20, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "rock"},
    "Ampithoe rubricata":         {"salinity_min": 3, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "plant"},
    "Einhornia crustulenta":      {"salinity_min": 3, "salinity_max": 25, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Dreissena polymorpha":       {"salinity_min": 0, "salinity_max": 8,  "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Heterotanais oerstedii":     {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "plant"},
    "Streblospio shrubsolii":     {"salinity_min": 3, "salinity_max": 25, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Monocorophium insidiosum":   {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "plant"},
    # ── DEEP BRACKISH PROFUNDAL (glacial relicts) ───────────────────────────────
    "Mysis mixta":                {"salinity_min": 2, "salinity_max": 15, "sal_midpoint": 7,  "depth_zone": "profundal",      "functional_group": "predator",              "substrate": "pelagic"},
    "Mysis relicta":              {"salinity_min": 2, "salinity_max": 10, "sal_midpoint": 4,  "depth_zone": "profundal",      "functional_group": "predator",              "substrate": "pelagic"},
    "Monoporeia affinis":         {"salinity_min": 2, "salinity_max": 10, "sal_midpoint": 4,  "depth_zone": "profundal",      "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Saduria entomon":            {"salinity_min": 2, "salinity_max": 15, "sal_midpoint": 6,  "depth_zone": "profundal",      "functional_group": "predator",              "substrate": "soft"},
    "Halicryptus spinulosus":     {"salinity_min": 2, "salinity_max": 20, "sal_midpoint": 7,  "depth_zone": "profundal",      "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Pontoporeia femorata":       {"salinity_min": 2, "salinity_max": 10, "sal_midpoint": 4,  "depth_zone": "profundal",      "functional_group": "deposit_feeder",        "substrate": "soft"},
    # ── BRACKISH SOFT BOTTOM INFAUNA ─────────────────────────────────────────────
    "Bylgides sarsi":             {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Diastylis rathkei":          {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Ampharete acutifrons":       {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Micrura baltica":            {"salinity_min": 2, "salinity_max": 15, "sal_midpoint": 7,  "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Priapulus caudatus":         {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Ampharete baltica":          {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Scoloplos armiger":          {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Ophelia rathkei":            {"salinity_min": 5, "salinity_max": 20, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Alkmaria romijni":           {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Microphthalmus sczelkowii":  {"salinity_min": 0, "salinity_max": 20, "sal_midpoint": 6,  "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Alitta succinea":            {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Tubificoides benedii":       {"salinity_min": 2, "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Tubificoides pseudogaster":  {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Baltidrilus costatus":       {"salinity_min": 2, "salinity_max": 15, "sal_midpoint": 6,  "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Capitella capitata":         {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Polydora cornuta":           {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Arenicola marina":           {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 20, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Scrobicularia plana":        {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Spio arndti":                {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Rangia cuneata":             {"salinity_min": 2, "salinity_max": 15, "sal_midpoint": 7,  "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    # ── INTERMEDIATE SALINITY ALGAE + FAUNA ─────────────────────────────────────
    "Polyides rotunda":           {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Fabricia stellaris":         {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "suspension_feeder",     "substrate": "mixed"},
    "Aglaothamnion tenuissimum":  {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Ceramium diaphanum":         {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Desmarestia viridis":        {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Astarte elliptica":          {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Lagis koreni":               {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "suspension_feeder",     "substrate": "sand"},
    "Mya truncata":               {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 20, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Apherusa bispinosa":         {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "plant"},
    "Ericthonius brasiliensis":   {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "suspension_feeder",     "substrate": "rock"},
    "Lamprops fasciatus":         {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Opercularella lacerata":     {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "epibenthic",            "substrate": "rock"},
    "Bittium reticulatum":        {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "plant"},
    "Nemalion multifidum":        {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "littoral",       "functional_group": "macroalga",             "substrate": "rock"},
    "Astarte montagui":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 24, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Astarte borealis":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 24, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    # ── SUBTIDAL HIGHER SALINITY MACROALGAE ─────────────────────────────────────
    "Laminaria digitata":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Saccharina latissima":       {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Laminaria hyperborea":       {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Phycodrys rubens":           {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Delesseria sanguinea":       {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Phyllophora crispa":         {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Chondrus crispus":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Membranoptera alata":        {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Cystoclonium purpureum":     {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Sphaerotrichia divaricata":  {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Bryopsis hypnoides":         {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Bryopsis plumosa":           {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Chaetomorpha melagonium":    {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Sphacelaria cirrosa":        {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Dasya baillouviana":         {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Ulva lactuca":               {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Ulva linza":                 {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Fucus serratus":             {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Ascophyllum nodosum":        {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "littoral",       "functional_group": "macroalga",             "substrate": "rock"},
    "Halidrys siliquosa":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Desmarestia aculeata":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Callithamnion corymbosum":   {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    # ── KATTEGAT HIGH-SALINITY MACROALGAE ───────────────────────────────────────
    "Corallina officinalis":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Lithothamnion glaciale":     {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Odonthalia dentata":         {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Palmaria palmata":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Peyssonnelia dubyi":         {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Dasysiphonia japonica":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Sargassum muticum":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Bonnemaisonia asparagoides": {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Bonnemaisonia hamifera":     {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Pterothamnion plumula":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Ptilota gunneri":            {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Dilsea carnosa":             {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Heterosiphonia plumosa":     {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Asperococcus bullosus":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Derbesia marina":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Callithamnion tetragonum":   {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Spermothamnion repens":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Lomentaria clavellosa":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Rhodophyllis divaricata":    {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Erythrodermis traillii":     {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Melobesia membranacea":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Colaconema daviesii":        {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Colaconema pectinatum":      {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Colaconema nemalionis":      {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Plumaria plumosa":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Vertebrata byssoides":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Erythrotrichia carnea":      {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "plant"},
    "Scagelothamnion pusillum":   {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Sphaceloderma caespitulum":  {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Rubrointrusa membranacea":   {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Apoglossum ruscifolium":     {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Cruoria pellita":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "macroalga",             "substrate": "rock"},
    "Filellum serpens":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "epibenthic",            "substrate": "rock"},
    # ── KATTEGAT HARD SUBSTRATE INVERTEBRATES ───────────────────────────────────
    "Ascidiella aspersa":         {"salinity_min": 18,"salinity_max": 35, "sal_midpoint": 26, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Modiolus modiolus":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Halisarca dujardinii":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Metridium senile":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "epibenthic",            "substrate": "rock"},
    "Molgula manhattensis":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Clytia hemisphaerica":       {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "epibenthic",            "substrate": "plant"},
    "Callopora lineata":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Escharella immersa":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Spirorbis corallinae":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Crisia eburnea":             {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Eucratea loricata":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Sertularia cupressina":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "epibenthic",            "substrate": "rock"},
    "Farrella repens":            {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Electra pilosa":             {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "plant"},
    "Flustra foliacea":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Dendrodoa grossularia":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Psammechinus miliaris":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "rock"},
    "Asterias rubens":            {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Gammarellus homari":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "rock"},
    "Gattyana cirrhosa":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "rock"},
    "Tubulanus polymorphus":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "mixed"},
    # ── KATTEGAT SANDY BOTTOM / MIXED ───────────────────────────────────────────
    "Upogebia deltaura":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "suspension_feeder",     "substrate": "sand"},
    "Bathyporeia guilliamsonia":  {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Bathyporeia pelagica":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Phoxocephalus holbolli":     {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "sand"},
    "Branchiostoma lanceolatum":  {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Chamelea gallina":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Fabulina fabula":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Spiophanes bombyx":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Ophelia borealis":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Pisione remota":             {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "sand"},
    "Lanice conchilega":          {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "suspension_feeder",     "substrate": "sand"},
    "Nephtys longosetosa":        {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "sand"},
    "Spio filicornis":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Spio armata":                {"salinity_min": 5, "salinity_max": 30, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Mediomastus fragilis":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Aporrhais pespelecani":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Philline aperta":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Philine aperta":             {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Spisula subtruncata":        {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Macoma calcarea":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Echinocardium cordatum":     {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Echinocyamus pusillus":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Poecilochaetus serpens":     {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Thracia phaseolina":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Perioculodes longimanus":    {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Tellimya ferruginosa":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Ampelisca brevicornis":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    # ── MARINE SOFT BOTTOM MID-DEPTH ────────────────────────────────────────────
    "Harmothoe imbricata":        {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Parvicardium pinnulatum":    {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Parvicardium minimum":       {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Aricidea suecica":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Aricidea cerrutii":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Aricidea minuta":            {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Phyllodoce mucosa":          {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Corbula gibba":              {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Arctica islandica":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Trochochaeta multisetosa":   {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Kurtiella bidentata":        {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Phaxas pellucidus":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Heteromastus filiformis":    {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Terebellides stroemii":      {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Ampelisca macrocephala":     {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Crenella decussata":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "plant"},
    "Apistobranchus tullbergi":   {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Artacama proboscidea":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Abra alba":                  {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Nephtys ciliata":            {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Nephtys assimilis":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Nephtys pente":              {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Ophiura albida":             {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Parexogone hebes":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Lysilla loveni":             {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Musculus niger":             {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Musculus discors":           {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Nereimyra punctata":         {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Pherusa plumosa":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Halcampa duodecimcirrata":   {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "epibenthic",            "substrate": "soft"},
    "Pariambus typicus":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Protomedeia fasciata":       {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "plant"},
    "Polycirrus medusa":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Mya truncata":               {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 20, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Hiatella arctica":           {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Dipolydora quadrilobata":    {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Neoamphitrite figulus":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Spio goniocephala":          {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Crassicorophium crassicor":  {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Lineus ruber":               {"salinity_min": 5, "salinity_max": 25, "sal_midpoint": 12, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Laonome kroyeri":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Exogone naidina":            {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "plant"},
    "Onoba semicostata":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "rock"},
    "Malacobdella grossa":        {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "mixed"},
    "Pholoe assimilis":           {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Pholoe inornata":            {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Paraonis fulgens":           {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Tanaissus lilljeborgi":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "plant"},
    "Pusillina inconspicua":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "rock"},
    "Hermania scabra":            {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Philine quadripartita":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Laonice bahusiensis":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Paramphinome jeffreysii":    {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Ophelia rathkei":            {"salinity_min": 5, "salinity_max": 20, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Diastyloides biplicatus":    {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Eumida sanguinea":           {"salinity_min": 10,"salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "rock"},
    "Phyllodoce groenlandica":    {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Platynereis dumerilii":      {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "infralittoral",  "functional_group": "predator",              "substrate": "rock"},
    # ── DEEP CIRCALITTORAL / PROFUNDAL ──────────────────────────────────────────
    "Virgularia mirabilis":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "epibenthic",            "substrate": "soft"},
    "Brissopsis lyrifera":        {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Harpinia antennaria":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Ampelisca diadema":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Glycinde nordmanni":         {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Golfingia vulgaris":         {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Diastylis laevis":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Praxillella affinis":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Rhodine loveni":             {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Eudorella emarginata":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Prionospio multibranchiat":  {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Magelona minuta":            {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Anobothrus gracilis":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Pectinaria belgica":         {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Brada villosa":              {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Labidoplax buskii":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Polyphysia crassa":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Acanthocardia echinata":     {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Trichobranchus roseus":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Westwoodilla caecula":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Sphaerodorum gracilis":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Tellimya tenella":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Polycirrus plumosus":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Praxillella praetermissa":   {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Rhodine gracilior":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Chaetoderma nitidulum":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Maldane sarsi":              {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Chalinula limbata":          {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "rock"},
    "Eudorella truncatula":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Levinsenia gracilis":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Paradoneis eliasoni":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Polycirrus norvegicus":      {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Galathowenia oculata":       {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Prionospio fallax":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Phyllodoce rosea":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Amphiura filiformis":        {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Eumida bahusiensis":         {"salinity_min": 15,"salinity_max": 30, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Glycera alba":               {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Nucula nitidosa":            {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Thyasira flexuosa":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Abyssoninoe hibernica":      {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Oxydromus flexuosus":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Glycera unicornis":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Abra nitida":                {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Ennucula tenuis":            {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Dosinia exoleta":            {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "sand"},
    "Notomastus latericeus":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Cylichna cylindracea":       {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Turritella communis":        {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Owenia fusiformis":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "sand"},
    "Edwardsia longicornis":      {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "epibenthic",            "substrate": "soft"},
    "Mysia undata":               {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",         "substrate": "soft"},
    "Magelona alleni":            {"salinity_min": 25,"salinity_max": 35, "sal_midpoint": 30, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "sand"},
    "Pholoe baltica":             {"salinity_min": 15,"salinity_max": 25, "sal_midpoint": 18, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Chaetozone setosa":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Goniada maculata":           {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",              "substrate": "soft"},
    "Scalibregma inflatum":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Tharyx killariensis":        {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Phoronis muelleri":          {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    "Plagiospora gracilis":       {"salinity_min": 20,"salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",        "substrate": "soft"},
    "Polycirrus medusa":          {"salinity_min": 15,"salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",     "substrate": "soft"},
    # ── OTHER MISC ──────────────────────────────────────────────────────────────
    "Opercularella lacerata":     {"salinity_min": 5, "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "epibenthic",            "substrate": "rock"},
}

# Genus-level fallbacks for taxa not covered above
GENUS_FALLBACKS = {
    "Chara":        {"salinity_min": 0,  "salinity_max": 12, "sal_midpoint": 3,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte", "substrate": "soft"},
    "Potamogeton":  {"salinity_min": 0,  "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte", "substrate": "soft"},
    "Nitella":      {"salinity_min": 0,  "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte", "substrate": "soft"},
    "Callitriche":  {"salinity_min": 0,  "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte", "substrate": "soft"},
    "Ranunculus":   {"salinity_min": 0,  "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "infralittoral",  "functional_group": "submerged_macrophyte", "substrate": "soft"},
    "Eleocharis":   {"salinity_min": 0,  "salinity_max": 5,  "sal_midpoint": 1,  "depth_zone": "littoral",       "functional_group": "emergent_macrophyte",  "substrate": "soft"},
    "Fontinalis":   {"salinity_min": 0,  "salinity_max": 3,  "sal_midpoint": 0,  "depth_zone": "infralittoral",  "functional_group": "macroalga",            "substrate": "rock"},
    "Ceramium":     {"salinity_min": 3,  "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "macroalga",            "substrate": "rock"},
    "Polysiphonia": {"salinity_min": 3,  "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "macroalga",            "substrate": "rock"},
    "Ulva":         {"salinity_min": 5,  "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",            "substrate": "rock"},
    "Cladophora":   {"salinity_min": 0,  "salinity_max": 30, "sal_midpoint": 10, "depth_zone": "infralittoral",  "functional_group": "macroalga",            "substrate": "rock"},
    "Nephtys":      {"salinity_min": 10, "salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "predator",             "substrate": "soft"},
    "Aricidea":     {"salinity_min": 10, "salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",       "substrate": "soft"},
    "Ampelisca":    {"salinity_min": 15, "salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",    "substrate": "soft"},
    "Glycera":      {"salinity_min": 20, "salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "predator",             "substrate": "soft"},
    "Spio":         {"salinity_min": 5,  "salinity_max": 35, "sal_midpoint": 15, "depth_zone": "infralittoral",  "functional_group": "deposit_feeder",       "substrate": "soft"},
    "Phyllodoce":   {"salinity_min": 10, "salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "predator",             "substrate": "soft"},
    "Gammarus":     {"salinity_min": 0,  "salinity_max": 25, "sal_midpoint": 8,  "depth_zone": "infralittoral",  "functional_group": "predator",             "substrate": "mixed"},
    "Praxillella":  {"salinity_min": 20, "salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",       "substrate": "soft"},
    "Rhodine":      {"salinity_min": 20, "salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",       "substrate": "soft"},
    "Magelona":     {"salinity_min": 20, "salinity_max": 35, "sal_midpoint": 28, "depth_zone": "circalittoral",  "functional_group": "deposit_feeder",       "substrate": "sand"},
    "Astarte":      {"salinity_min": 10, "salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",        "substrate": "soft"},
    "Colaconema":   {"salinity_min": 10, "salinity_max": 35, "sal_midpoint": 22, "depth_zone": "infralittoral",  "functional_group": "macroalga",            "substrate": "rock"},
    "Callithamnion":{"salinity_min": 5,  "salinity_max": 35, "sal_midpoint": 18, "depth_zone": "infralittoral",  "functional_group": "macroalga",            "substrate": "plant"},
    "Polycirrus":   {"salinity_min": 15, "salinity_max": 35, "sal_midpoint": 25, "depth_zone": "circalittoral",  "functional_group": "suspension_feeder",    "substrate": "soft"},
    "Parvicardium": {"salinity_min": 10, "salinity_max": 35, "sal_midpoint": 22, "depth_zone": "circalittoral",  "functional_group": "filter_feeder",        "substrate": "soft"},
}

# Zone salinity expectations (PSU ranges and midpoints)
ZONE_SALINITY = {
    "Zone1": {"min": 0,  "max": 3,  "midpoint": 1.5},
    "Zone2": {"min": 3,  "max": 6,  "midpoint": 4.5},
    "Zone3": {"min": 6,  "max": 12, "midpoint": 9.0},
    "Zone4": {"min": 12, "max": 31, "midpoint": 21.5},
}
